"""Report rendering: HTML (Jinja2) and PDF (reportlab, pure-python)."""
from __future__ import annotations

import io

from jinja2 import Template

_STATUS_COLOR = {"pass": "#15803d", "warn": "#b45309", "fail": "#b91c1c", "info": "#475569"}

_HTML = Template(
    """<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>AegisScan report - {{ r.hostname }}</title>
<style>
 body{font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;color:#0f172a;max-width:820px;margin:2rem auto;padding:0 1rem}
 .grade{font-size:3rem;font-weight:800}
 .cat{margin:1.5rem 0;border:1px solid #e2e8f0;border-radius:10px;padding:1rem}
 .f{padding:.5rem 0;border-top:1px solid #f1f5f9}
 .pill{display:inline-block;padding:.05rem .5rem;border-radius:999px;color:#fff;font-size:.75rem;font-weight:700;text-transform:uppercase}
 code{background:#f1f5f9;padding:.1rem .35rem;border-radius:4px}
 .fix{color:#334155;font-size:.9rem}
</style></head><body>
 <h1>{{ r.hostname }}</h1>
 <div class="grade" style="color:{{ gradecolor }}">{{ r.grade }}</div>
 <p>Score {{ r.score }}/100 &middot; {{ r.summary.pass }} pass &middot; {{ r.summary.warn }} warn &middot; {{ r.summary.fail }} fail &middot; engine {{ r.engine_version }}</p>
 {% for c in r.categories %}
 <div class="cat"><h2>{{ c.label }} <small>({{ c.score }}/{{ c.max_score }})</small></h2>
   {% for f in c.findings %}
   <div class="f"><span class="pill" style="background:{{ colors[f.status] }}">{{ f.status }}</span>
     <strong>{{ f.title }}</strong>
     <div>{{ f.detail }}</div>
     {% if f.fix %}<div class="fix">Fix: <code>{{ f.fix }}</code></div>{% endif %}
     {% if f.owasp %}<div class="fix">OWASP: {{ f.owasp|join(', ') }}</div>{% endif %}
   </div>
   {% endfor %}
 </div>
 {% endfor %}
 <p style="color:#94a3b8">Generated by AegisScan. Passive, read-only inspection.</p>
</body></html>"""
)


def build_html(result: dict) -> str:
    return _HTML.render(r=result, colors=_STATUS_COLOR, gradecolor=_grade_color(result["grade"]))


def _grade_color(grade: str) -> str:
    return {"A+": "#15803d", "A": "#15803d", "B": "#65a30d", "C": "#b45309", "D": "#ea580c"}.get(grade, "#b91c1c")


def build_pdf(result: dict) -> bytes:
    from reportlab.lib.colors import HexColor
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title=f"AegisScan - {result['hostname']}")
    styles = getSampleStyleSheet()
    story = [
        Paragraph(f"AegisScan report &mdash; {result['hostname']}", styles["Title"]),
        Paragraph(
            f"<b>Grade {result['grade']}</b> &nbsp; Score {result['score']}/100 &nbsp; "
            f"({result['summary']['pass']} pass / {result['summary']['warn']} warn / "
            f"{result['summary']['fail']} fail)",
            styles["Normal"],
        ),
        Spacer(1, 6 * mm),
    ]
    for cat in result["categories"]:
        story.append(Paragraph(f"<b>{cat['label']}</b> ({cat['score']}/{cat['max_score']})", styles["Heading2"]))
        for f in cat["findings"]:
            color = _STATUS_COLOR.get(f["status"], "#475569")
            line = f'<font color="{color}"><b>[{f["status"].upper()}]</b></font> {f["title"]} &mdash; {f["detail"]}'
            story.append(Paragraph(line, styles["Normal"]))
            if f.get("fix"):
                story.append(Paragraph(f'<i>Fix:</i> <font face="Courier">{_esc(f["fix"])}</font>', styles["Normal"]))
            story.append(Spacer(1, 2 * mm))
        story.append(Spacer(1, 4 * mm))
    doc.build(story)
    return buf.getvalue()


def _esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
